// Copyright Off World Live Limited 2020-2025. All rights reserved.
#pragma once
#include "CoreMinimal.h"
#include "OWL360PipelineSettings.h"

#include "OWL360PipelineLauncher.generated.h"

class UOWL360CameraMoviePipelinePass;
class UMoviePipeline;
class UMoviePipelineQueue;
class UMoviePipelinePrimaryConfig;
class UMoviePipelineExecutorJob;
struct FOWLCameraCompositeSummary;


USTRUCT(BlueprintType)
struct FOWL360PipelineLauncher
{
	GENERATED_BODY()
public:
	FOWL360PipelineLauncher();
public:
	/* Root directory for the intermediate renders generated by each face */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Output", DisplayName="Intermediate Output Directory")
	FDirectoryPath OutputDirectoryRoot;

	/* Filename prefix for each intermediate face render - will overwrite existing files.
	 You can use:
		{job_name}
		{shot_name}
		{sequence_name}
		{author_name}
		{level_name} */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Output", DisplayName="Intermediate File Prefix")
	FString FilePrefix = "{sequence_name}_";

	/* Prefix for the name jobs that will be created to render each face and stitch them together */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Output")
	FString JobNamePrefix = "360_";

	/* Delete the intermediate files once stitching has completed successfully*/
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Output")
	bool bDeleteIntermediatesAfterStitch = false;

	/* Total Tiles per face to generate. Caution: this may add additional seams */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Output")
	FIntPoint Tiles = FIntPoint(1);

	/* When using tiles, use the overlap percent to reduce seams between the tiles */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Output", meta=(UIMin=0, UIMax=50, ClampMin=0, ClampMax=50))
	float TileOverlapPercent = 5;

	/* When using tiles, it may be useful to set a minimum dimension. This ensures that some post-process effects work correctly */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Output")
	int MinimumTileDimension = 10;

	/* Sets the number of concurrent stitch jobs. Stitching is currently single-threaded so running multiple conncurrent
	 stitches makes better use of CPU resources, however, very high resolution stitches occupy a lot of ram.
	 For very high res stitches, we recommend a max concurrent value of 1 */
	UPROPERTY(EditAnywhere, Category="Output", meta=(UIMin=0,UIMax=20, ClampMin=0, ClampMax=20))
	int MaxConcurrentStitches;

	/* When rendering long sequences, sometimes it may be useful to execute the stitch on a subset sequence
	 before continuing. This may be useful to preview the output as it is being rendered to validate the output quality.
	 This creates a separate job for each frame range and can lead to a lot of jobs. Be aware that this
	 will add time to your total render as each job will require an additional warmup sequence before it starts */
	UPROPERTY(EditAnywhere, Category="Output")
	bool bBreakJobsByFrameRange = false;

	/* The number of frames per job */
	UPROPERTY(EditAnywhere, Category="Output", meta=(EditCondition="bBreakJobsByFrameRange", EditConditionHides))
	int FrameRangePerJob = 50;

	/* Output debug exr files with metadata on intermediate jobs. This writes out an extra intermediate
	 file in .exr format and a .meta text file with a summary of the included metadata in human-readable
	 format for debugging purposes */
	UPROPERTY(EditAnywhere, Category="Output")
	bool bWriteIntermediateDebugFiles = false;

public:
	bool bDisplayLauncherButton = true;

public:
#if WITH_EDITOR
	void Generate360Queue(UOWL360CameraMoviePipelinePass* BasePass);
	static TArray<TRange<int>> GetFrameRanges(const TRange<FFrameNumber>& PlaybackRange, int FrameRangePerJob);
	bool GenerateJobsForRange(
		const UOWL360CameraMoviePipelinePass* BasePass,
		UMoviePipelineQueue* Queue,
		UMoviePipelinePrimaryConfig*  PrimaryConfig,
		const UMoviePipelineExecutorJob* SrcJob,
		const TRange<int>* Range,
		FOWL360PipelineSettings& PipelineSettings,
		const TArray<FOWLCameraCompositeSummary>& CompositeCameras, bool bRenderAllCameras, const FFrameRate&
		SequenceFrameRate, const FFrameRate& TickResolution) const;
	static void SetCustomRange(UMoviePipelinePrimaryConfig* Config, const TRange<int>* Range);
	static bool HasCrops(const TArray<FOWLFoundSequenceCamera>& Cameras);
	bool ShouldRenderFace(const FOWLFoundSequenceCamera& Camera, int FaceIndex) const;
	bool ShouldRenderTile(FOWL360PipelineSettings& Settings, const FOWLFoundSequenceCamera& Camera, int FaceIndex, int TileX, int TileY) const;
#endif
	static FString FormatPrefix(const FString& Format, const UMoviePipeline* Pipeline, const FString& ShotName);
};

