;METADATA=(Diff=true, UseCommands=true)
[/Script/LivestreamingToolkit.OWLSettings]
bAutoLaunchNDIInstaller=False
bDisableHardwareEncoding=False
bSuppressLoginPopup=False
bUseApplicationLicense=False
bEnableOWLDemoLicences=False
bDemoLicencePopupDismissed=True
OWLOfflineAppData=
OWLCameraRenderOutputPath=../../../../../UNRProj/Summer2026Research/Saved/OWLCameraOutput

[/Script/EngineSettings.GeneralProjectSettings]
bShouldWindowPreserveAspectRatio=False
bUseBorderlessWindow=True

